### ISSUE TITLE
Name of the primary key should be flexible

### ISSUE THREAD

**Issue by pvoznenko** [guardian/scanamo#25]
Hi @philwills , 

First of all thank you for sharing this library!

Unfortunately playing with it, I found a bug.

You can create table and use table only if primary key have name `name`.

Otherwise you will get an error ```com.amazonaws.AmazonServiceException, with message: One of the required keys was not given a value (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException;```

You can easy reproduce this bug by changing, for example, `ScanamoAsyncTest` "should put asynchronously":

```scala
LocalDynamoDB.usingTable(client)("asyncFarmers")('somethingElse -> S) {
      ...
      case class Farmer(somethingElse: String, age: Long, farm: Farm)
```

Thank you again for the library,
Best Regards,
Pavlo

**Comment by philwills** [comment]
It's not the case that the hash key is hardcoded. I've just pushed up a branch changing that test and I suspect you missed also changing the key in the `get` call, here: https://github.com/guardian/scanamo/blob/nom/src/test/scala/com/gu/scanamo/ScanamoAsyncTest.scala#L26

You can see the tests still pass: https://travis-ci.org/guardian/scanamo/builds/126934943

However, that it fails with a slightly cryptic exception like that in such a situation isn't something I'm happy about and I hope to provide better errors in the future. Ideally I'd find a way of constraining the grammar so that you can't compile an invalid query like that.

**Comment by pvoznenko** [comment]
Thanks for quick reply! You are right, I missed it totally.

Thanks!
