### ISSUE TITLE
Support batch deletion

### ISSUE THREAD

**Issue by joprice** [guardian/scanamo#27]
There is `putAll` and `getAll`, would `deleteAll` make sense as well? This doc also demonstrates a mix of puts and deletes:

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/batch-operation-document-api-java.html

Perhaps there could be syntax for mixing the two like `batch(put = List(...), delete = List(...))`

**Comment by philwills** [comment]
A `deleteAll` would be a good addition. 

Mixing the two seems a bit odd to me and I haven't seen any compelling uses in the wild, so I'm not yet convinced it's worth the complexity.

**Comment by joprice** [comment]
I have at one use case for it so far that corresponds to a user on a mobile device modifying a list of items and sending a batch of modifications and removals. But it's probably a rare use case.

**Comment by randallalexander** [comment]
@philwills we have a working version of deleteAll based off the putAll that we would be willing to contribute back.  My main question is what do you think the result should be?  Our version tries to go through the result and figure out what was actually deleted and return that.  (Since the AWS result does return unprocessed items https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html)  Alternatively we could just return the unprocessed items, the BatchWriteItemResult, or any other variant you can think of.  I am open to whatever you think is more inline with the library design.  Let me know and I will work on a PR for it.

**Comment by philwills** [comment]
This is now supported as of 0.8.2
